#+SHOW_ALL
#+TITLE Far Side
#+AUTOR Роман Зайруллин

* CRPG. Введение
  Этот документ содержит все. И предусматривает все.
  Вдохновленный Shadowrun, Fallout, ADOM и различными TDS, я хочу поместить
  вас в мир, в котором нет магии, зато есть пар и электричество. И,
  может быть, немного клюквы. Ну и нефть еще. И вообще много всяких
  интересных штук
** Инструменты и начальный набор функций.

* Ролевая система
  Проблема выбора ролевой системы в наличии магии у большинства
  РПГ. Я, конечно, поклонник фентези, но в своем проекте использовать
  ее не хочу. На самом деле, это ж уже достаточно приевшаяся тема и
  кто только не делает РПГ с магией и красотками. Я же хочу окунуться
  в мир альтернативной истории в компании с Говардом Радостью-моим
  Лавкрафтом.
  Итак. Характеристики. (d10 при создании, с
  возможностью корректировки)
  - Сила    
  - Ловкость  
  - Интеллект
  - Внимательность (?)
  - Здоровье
  - Удача
  - Сущность[fn:1]
  Так же, каждый персонаж должен иметь инвентарь (чтоб безумным манчам
  было откуда собирать лут).
  Помимо основных характеристик, персонажи так же имеют различные навыки
  различные навыки:
  - Оружие, боевые навыки
    * Холодное
    * Огнестрельное
    * Рукопашный бой
  - Техника
    * Взлом
    * Ремонт
    * Изобретательство
  - Исследованияттт
  - Люди
    * Кража
    * Ложь
    * Убеждение
    * Хитрость
  - Медицина
    * Хирургия
    * Первая помощь
  Так же, естественно, каждый персонаж имеет имя, пол, вид (человек,
  собака, дерево) и описание.
#+begin_src python game-classes.py
# -*- coding: utf-8 -*-
class character:
 def __init__(self, charahter-name, description, sort, sex, states, level, inventory, perks):
 states = { 'strength': 0, 'agility': 0, 'intelegence': 0, 'health': 0, 'luck': 0, 'nature': 0}
 invetory = []
 perks = { 'meele-weapon': 0, 'guns': 0, 'meele': 0, 
           'breaking': 0, 'repair': 0, 'investigation': 0, 
           'research': 0, 
           'stealing': 0, 'lie': 0, 'conviction':0, 'tricks':0,
           'surgeons': 0, 'first-aid': 0}
 description = []
 sort = []
#+end_src

* Сеттинг
  
* Сценарий
  
* Таблицы

** НПС
** Бестиарий
** Предметы
*** Оружие
*** Одежда
*** Инструменты
*** Расходуемые
*** Хлам

* Локации
  
* Звук 
** libpd и прочее
   Конечно, процедурный синтез, во многом, это все затевается ради
   него. Помимо, конечно, изменяющегося, в зависимости от
   происходящего, саундтрека. Мне хочется полностью обойтись без
   предзаписанного звука. Это позволит использовать разнообразное
   окружение, гибкое и интересное. И при этом игра не будет много
   весить.

* Footnotes

[fn:1] Изначально я хотел включить сюда харизму, но впоследствии
отказался, так как иначе это бы это вышел SPETIAL, да и система
разговорных навыков + репутация выглядит более
привлекательной. Особенно, если в игре будет активное социальное взаимодействие.

