#+SHOW_ALL
#+TITLE Far Side
#+AUTOR Роман Зайруллин

* CRPG. Введение
  Этот документ содержит все. И предусматривает все.
  Вдохновленный Shadowrun, Fallout, ADOM и различными TDS, я хочу поместить
  вас в мир, в котором нет магии, зато есть пар и электричество. И,
  может быть, немного клюквы. Ну и нефть еще. И вообще много всяких
  интересных штук
** Инструменты и начальный набор функций.

* Ролевая система
  Проблема выбора ролевой системы в наличии магии у большинства
  РПГ. Я, конечно, поклонник фентези, но в своем проекте использовать
  ее не хочу. На самом деле, это ж уже достаточно приевшаяся тема и
  кто только не делает РПГ с магией и красотками. Я же хочу окунуться
  в мир альтернативной истории в компании с Говардом Радостью-моим
  Лавкрафтом.
  
* Сеттинг

* Сценарий
  
* Таблицы

** НПС
** Бестиарий
** Предметы
*** Оружие
*** Одежда
*** Инструменты
*** Расходуемые
*** Хлам

* Локации
  
* Звук 
** libpd и прочее
   Конечно, процедурный синтез, во многом, это все затевается ради
   него. Помимо, конечно, изменяющегося, в зависимости от
   происходящего, саундтрека. Мне хочется полностью обойтись без
   предзаписанного звука. Это позволит использовать разнообразное
   окружение, гибкое и интересное. И при этом игра не будет много весить.
